language: python

python:
  - "3.5"

install:
  - pip install .
  - pip install codecov
  - cp ci/testsettings.py testsettings.py
  - python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

script:
  - python setup.py test

after_success:
- codecov
