name: unit tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  schedule: # run automatically on main branch each Tuesday at 11am
    - cron: "0 16 * * 2"

jobs:
  python-unit:
    name: Python unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.9", "3.10", "3.11"]
        django: ["3.2", "4.0", "4.1", "4.2"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install package with dependencies
        run: |
          uv pip install --system -e .
          uv pip install --system -e '.[test]'
          uv pip install --system "django~=${{ matrix.django }}"

      - name: Setup test settings
        run: |
          cp ci/testsettings.py testsettings.py
          python -c "import uuid; print('SECRET_KEY = \'%s\'' % uuid.uuid4())" >> testsettings.py

      - name: Run pytest
        run: pytest --cov=pucas --cov-report=xml --cov-report=term

      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: false
